services:
  leadbot:
    build:
      context: .
    image: leadbot:latest
    container_name: leadbot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ADMIN_CHAT_ID: ${TELEGRAM_ADMIN_CHAT_ID}
      TELEGRAM_ORDER_CHAT_ID: ${TELEGRAM_ORDER_CHAT_ID}
      TELEGRAM_BOT_DEMO: ${TELEGRAM_BOT_DEMO}
    restart: unless-stopped
